image: php:8.0.12-cli

stages:
  - test
  - coverage
  - sonarqube_check
  - sonarqube_scan

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - vendor/
    - .m2/repository
    - target/

variables:
  SONAR_TOKEN: "989c7a1c5ab516c4f1f075255da3fa8d26d14c05"

before_script:
  - test -d vendor || apt-get update -yqq
  - test -d vendor || apt-get install -yqq curl git libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libonig-dev libzip-dev
  - test -d vendor || docker-php-ext-install mbstring pdo_pgsql curl intl gd xml zip bz2
  - test -d vendor || curl -sS https://getcomposer.org/installer | php
  - test -d vendor || php composer.phar install

test:
  stage: test
  script:
   - vendor/bin/phpunit --bootstrap src/autoload.php --colors=never --log-junit phpunit-report.xml --coverage-clover=coverage.xml tests
  allow_failure: true
  artifacts:
    when: always
    reports:
      junit: phpunit-report.xml
    paths:
      - coverage.xml
 
coverage:
  stage: coverage
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - phpunit --coverage-clover=coverage.xml
  
sonarqube-check:
  stage: sonarqube_check
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner

sonarqube_scan:
  stage: sonarqube_scan
  script:
    - DownloadFile https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-windows.zip -OutFile sonar-scanner-cli-4.6.0.2311-windows.zip
    - Expand-Archive -Path sonar-scanner-cli-4.6.0.2311-windows.zip -DestinationPath $env:CI_PROJECT_DIR
    - $env:PATH += ";$env:CI_PROJECT_DIR\sonar-scanner-cli-4.6.0.2311-windows\bin"
    - sonar-scanner -Dsonar.projectKey=$env:CI_PROJECT_NAME -Dsonar.organization=jeremymartin87-1 -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$env:SONAR_TOKEN -Dsonar.php.coverage.reportPaths=coverage.xml
