image: php:8.0.12-cli

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - vendor/
    - .m2/repository
    - target/

variables:
  SONAR_TOKEN: "989c7a1c5ab516c4f1f075255da3fa8d26d14c05"

before_script:
  - test -d vendor || apt-get update -yqq
  - test -d vendor || apt-get install -yqq curl git libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev libonig-dev libzip-dev
  - test -d vendor || docker-php-ext-install mbstring pdo_pgsql curl intl gd xml zip bz2
  - test -d vendor || curl -sS https://getcomposer.org/installer | php
  - test -d vendor || php composer.phar install

test:
  script:
   - vendor/bin/phpunit --bootstrap src/autoload.php --colors=never --log-junit phpunit-report.xml tests
  allow_failure: true
  artifacts:
    when: always
    reports:
      junit: phpunit-report.xml

coverage:
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - phpunit --coverage-clover=coverage.xml

sonarqube_scan:
  script:
    - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.organization=jeremymartin87-1 -Dsonar.sources=src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.php.coverage.reportPaths=coverage.xml
